present errors: 1. after line53, there is no pause in the program for the user to click 'enter' to continue. 2. lines 65 and 68 are skipped; program jumps to line 72.
current exceptions post line 72:
Exception in thread "Thread-2" Exception in thread "Thread-0" Exception in thread "Thread-1" Exception in thread "Thread-3" java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.add(Object)" because "this.processingQueue" is null
        at Inventory.addItem(Inventory.java:9)
        at Purchaser.run(Purchaser.java:22)
Exception in thread "Thread-4" java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.add(Object)" because "this.processingQueue" is null
        at Inventory.addItem(Inventory.java:9)
        at Purchaser.run(Purchaser.java:22)
java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.add(Object)" because "this.processingQueue" is null
        at Inventory.addItem(Inventory.java:9)
        at Purchaser.run(Purchaser.java:22)
java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.add(Object)" because "this.processingQueue" is null
        at Inventory.addItem(Inventory.java:9)
        at Purchaser.run(Purchaser.java:22)
java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.add(Object)" because "this.processingQueue" is null
        at Inventory.addItem(Inventory.java:9)
        at Purchaser.run(Purchaser.java:22)